default: --tags ~@selenium,~@wip --exclude features/support/selenium.rb --exclude features/step_definitions/selenium_steps.rb -r features/support -r features/step_definitions
selenium: --tags @selenium,~@wip -r features/support -r features/step_definitions
